name: Build & Publish GridWatch Image

on:
  workflow_dispatch:
  push:
    tags:
      - v*.*.*-gridwatch-*

env:
  REPO: gcr.io/powerwatch-backend/nline-grafana-image

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCLOUD_JSON }}

      - name: Configure Docker for GCR
        run: |
          gcloud --quiet auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REPO }}:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max